[project]
name = "py-hamt"
version = "1.1.1"
description = "HAMT Implementation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "hypothesis>=6.115.5",
    "pdoc>=15.0.0",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "ruff>=0.7.1",
    "snakeviz>=2.2.0",
]
