[project]
name = "py-hamt"
version = "1.1.1"
description = "HAMT Implementation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest-cov>=5.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "hypothesis>=6.115.5",
    "pdoc>=15.0.0",
    "pytest>=8.3.3",
    "ruff>=0.7.1",
]
