name: Check linting and formatting
run-name: Check linting and formatting , triggered on push from ${{ github.actor }} to branch/tag ${{ github.ref_name }}
on: push

jobs:
  linting_and_formatting:
    name: Check linting and formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create project environment
        run: uv sync

      - name: Check linting with ruff
        run: uv run ruff check

      - name: Check formatting with ruff
        run: uv run ruff format --check
