name: Run checks
run-name: Triggered on push from ${{ github.actor }} to branch/tag ${{ github.ref_name }}
on: push
# Should be the same as py-hamt/run-checks.sh

jobs:
  run_checks:
    name: Create project environment, run all checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create project environment
        run: uv sync

      - name: Install IPFS
        uses: ibnesayeed/setup-ipfs@master
        with:
          ipfs_version: "0.32.1"
          run_daemon: true
        id: ipfs_setup


      - name: Install and configure Nginx
        run: |
          # Install Nginx
          sudo apt-get update
          sudo apt-get install -y nginx

          # Create Nginx config for reverse proxy with auth
          cat <<EOF | sudo tee /etc/nginx/sites-available/ipfs
          server {
              listen 5002;
              server_name localhost;

              location /api/v0/ {
                  # Enforce X-API-Key for API key auth
                  if (\$http_x_api_key != "test") {
                      return 401 "Unauthorized: Invalid or missing X-API-Key";
                  }

                  # Proxy to IPFS RPC API
                  proxy_pass http://127.0.0.1:5001;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }
          EOF

          # Enable the site and remove default
          sudo ln -s /etc/nginx/sites-available/ipfs /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default

          # Test Nginx config
          sudo nginx -t
     
     - name: Start Nginx and restart IPFS daemon
        run: |
          # Start Nginx
          sudo systemctl start nginx

          # Restart IPFS daemon to ensure it’s running
          ipfs shutdown
          ipfs daemon &

          # Wait for IPFS and Nginx to be ready
          sleep 5

      - name: Run pytest with coverage
        run: uv run pytest --cov=py_hamt tests/ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check coverage
        run: uv run coverage report --fail-under=100 --show-missing

      - name: Check linting with ruff
        run: uv run ruff check

      - name: Check formatting with ruff
        run: uv run ruff format --check
