name: Run checks
run-name: Triggered on push from ${{ github.actor }} to branch/tag ${{ github.ref_name }}
on: push

jobs:
  run_checks:
    name: Create project environment, run all checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create project environment
        run: uv sync

      - name: Call pytest
        run: uv run pytest

      - name: Check linting with ruff
        run: uv run ruff check

      - name: Check formatting with ruff
        run: uv run ruff format --check
