name: Run checks
run-name: Triggered on push from ${{ github.actor }} to branch/tag ${{ github.ref_name }}
on: push
# Should be the same as py-hamt/run-checks.sh

jobs:
  run_checks:
    name: Create project environment, run all checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6
        with:
          version: "latest"

      - name: Create project environment
        run: uv sync

      - name: Install IPFS
        uses: oduwsdl/setup-ipfs@e92fedca9f61ab9184cb74940254859f4d7af4d9 # v0.6.3
        with:
          ipfs_version: "0.34.1"
          run_daemon: true

      - name: Run pytest with coverage
        run: uv run pytest --cov=py_hamt tests/ --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check coverage
        run: uv run coverage report --fail-under=100 --show-missing

      - name: Check linting with ruff
        run: uv run ruff check

      - name: Check formatting with ruff
        run: uv run ruff format --check
