name: Run tests
run-name: Test suite running on push from {{ github.actor }} to branch/tag {{ github.ref_name }}
on: push

jobs:
  run_tests:
    name: Install uv, run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create project environment
        run: uv sync

      - name: Call pytest
        run: uv run pytest
